spring.application.name=Chon lich thi
server.port=3000

spring.h2.console.enabled=true
# default path: h2-console
spring.h2.console.path=/h2-ui
 
 
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

 
# App Properties
kltn.app.jwtCookieName=kltn
kltn.app.jwtSecret= ======================BezKoder=Spring===========================
kltn.app.jwtExpirationMs=86400000

springbootwebfluxjjwt.password.encoder.secret=thisissecret
springbootwebfluxjjwt.password.encoder.iteration=33
springbootwebfluxjjwt.password.encoder.keylength=256

springbootwebfluxjjwt.jjwt.secret=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave65ByteLength
springbootwebfluxjjwt.jjwt.expiration=28800

spring.security.oauth2.client.registration.google.client-id=426996587219-c43sp9jps1kkimtdgnk5619hteht0tks.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://45.122.253.162:3306/chonlichthilai

spring.datasource.username=chonlichthilai
spring.datasource.password=thanglong..2030
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

# Giới hạn kích thước file tải lên
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Giới hạn dung lượng request body
server.tomcat.max-swallow-size=100MB
server.tomcat.max-http-form-post-size=100MB

#-----------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thanhnx@thanglong.edu.vn
spring.mail.password=qtzhzhbtkjdyrvqk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
##rbkb qqcz cuvt cpmj

